import type { Config } from 'tailwindcss'

export default {
  content: ['./index.html', './src/**/*.{ts,tsx}'],
  theme: {
    // design tokens — the single source of visual styling values (TSD S-0001.01)
    // Apex Core design system — chosen via UI prototype, see branch prototype/apex-core-ui
    screens: {
      sm: '375px',
      md: '768px',
      lg: '1280px',
    },
    extend: {
      colors: {
        'surface-container-highest': '#31353e',
        'secondary-fixed': '#acedff',
        'inverse-on-surface': '#2c3039',
        'secondary-fixed-dim': '#4cd7f6',
        'on-primary-container': '#556d00',
        'tertiary-container': '#acf847',
        'tertiary-fixed': '#acf847',
        'secondary-container': '#03b5d3',
        'surface-container': '#1c2028',
        'on-primary-fixed-variant': '#3c4d00',
        'primary-fixed-dim': '#abd600',
        'surface-bright': '#353942',
        'outline-variant': '#444933',
        'on-secondary-fixed': '#001f26',
        error: '#ffb4ab',
        background: '#0f131c',
        'on-error-container': '#ffdad6',
        'surface-variant': '#31353e',
        'on-background': '#dfe2ee',
        'surface-container-low': '#181c24',
        'surface-container-lowest': '#0a0e16',
        surface: '#0f131c',
        'primary-container': '#c3f400',
        'tertiary-fixed-dim': '#91db2a',
        primary: '#ffffff',
        'primary-fixed': '#c3f400',
        'on-tertiary-fixed-variant': '#304f00',
        'on-secondary-fixed-variant': '#004e5c',
        'on-secondary': '#003640',
        'on-primary': '#283500',
        'on-tertiary-container': '#457000',
        'on-secondary-container': '#00424e',
        'on-error': '#690005',
        secondary: '#4cd7f6',
        'on-tertiary-fixed': '#102000',
        'inverse-primary': '#506600',
        tertiary: '#ffffff',
        'on-surface-variant': '#c4c9ac',
        'inverse-surface': '#dfe2ee',
        'error-container': '#93000a',
        'on-surface': '#dfe2ee',
        'on-tertiary': '#1f3700',
        outline: '#8e9379',
        'surface-tint': '#abd600',
        'on-primary-fixed': '#161e00',
        'surface-container-high': '#262a33',
        'surface-dim': '#0f131c',
      },
      borderRadius: {
        DEFAULT: '0.125rem',
        lg: '0.25rem',
        xl: '0.5rem',
        full: '0.75rem',
      },
      fontFamily: {
        display: ['"Space Grotesk"', 'sans-serif'],
        body: ['"Plus Jakarta Sans"', 'sans-serif'],
        'body-sm': ['"Plus Jakarta Sans"', 'sans-serif'],
        'label-caps': ['"Space Grotesk"', 'sans-serif'],
        'body-md': ['"Plus Jakarta Sans"', 'sans-serif'],
        'headline-lg': ['"Space Grotesk"', 'sans-serif'],
        'metric-huge': ['"Space Grotesk"', 'sans-serif'],
        'headline-sm': ['"Space Grotesk"', 'sans-serif'],
        'display-hero': ['"Space Grotesk"', 'sans-serif'],
        'headline-xl': ['"Space Grotesk"', 'sans-serif'],
        'label-md': ['"Plus Jakarta Sans"', 'sans-serif'],
        caption: ['"Plus Jakarta Sans"', 'sans-serif'],
        'metric-lg': ['"Space Grotesk"', 'sans-serif'],
        'metric-md': ['"Space Grotesk"', 'sans-serif'],
        'headline-md': ['"Space Grotesk"', 'sans-serif'],
        'body-lg': ['"Plus Jakarta Sans"', 'sans-serif'],
      },
      spacing: {
        xs: '0.25rem',
        sm: '0.5rem',
        md: '1rem',
        lg: '1.5rem',
        xl: '2rem',
        gutter: '1.5rem',
        margin: '2rem',
      },
      fontSize: {
        xs: ['0.75rem', { lineHeight: '1rem' }],
        sm: ['0.875rem', { lineHeight: '1.25rem' }],
        base: ['1rem', { lineHeight: '1.5rem' }],
        lg: ['1.125rem', { lineHeight: '1.75rem' }],
        xl: ['1.25rem', { lineHeight: '1.75rem' }],
        '2xl': ['1.5rem', { lineHeight: '2rem' }],
        // Apex Core type scale
        'display-hero': ['56px', { lineHeight: '64px', letterSpacing: '-0.03em', fontWeight: '700' }],
        'headline-xl': ['40px', { lineHeight: '48px', letterSpacing: '-0.02em', fontWeight: '700' }],
        'headline-lg': ['32px', { lineHeight: '40px', letterSpacing: '-0.02em', fontWeight: '700' }],
        'headline-md': ['24px', { lineHeight: '32px', letterSpacing: '-0.01em', fontWeight: '600' }],
        'headline-sm': ['20px', { lineHeight: '28px', letterSpacing: '0', fontWeight: '600' }],
        'metric-huge': ['48px', { lineHeight: '52px', letterSpacing: '-0.03em', fontWeight: '700' }],
        'metric-lg': ['32px', { lineHeight: '36px', letterSpacing: '-0.02em', fontWeight: '700' }],
        'metric-md': ['20px', { lineHeight: '24px', letterSpacing: '0', fontWeight: '600' }],
        'body-lg': ['18px', { lineHeight: '28px', fontWeight: '400' }],
        'body-md': ['15px', { lineHeight: '24px', fontWeight: '400' }],
        'body-sm': ['13px', { lineHeight: '20px', fontWeight: '400' }],
        'label-caps': ['11px', { lineHeight: '14px', letterSpacing: '0.12em', fontWeight: '700' }],
        'label-md': ['13px', { lineHeight: '18px', letterSpacing: '0.02em', fontWeight: '600' }],
        caption: ['11px', { lineHeight: '16px', letterSpacing: '0.01em', fontWeight: '500' }],
      },
    },
  },
  plugins: [],
} satisfies Config
