import type { Config } from 'tailwindcss'

export default {
  content: ['./index.html', './src/**/*.{ts,tsx}'],
  theme: {
    // design tokens — the single source of visual styling values (TSD S-0001.01)
    // Apex Core design system — chosen via UI prototype, see branch prototype/apex-core-ui
    screens: {
      sm: '375px',
      md: '768px',
      lg: '1280px',
    },
    extend: {
      colors: {
        surface: '#0f131c',
        'surface-dim': '#0f131c',
        'surface-bright': '#353942',
        'surface-container-lowest': '#0a0e16',
        'surface-container-low': '#181c24',
        'surface-container': '#1c2028',
        'surface-container-high': '#262a33',
        'surface-container-highest': '#31353e',
        'on-surface': '#dfe2ee',
        'on-surface-variant': '#c4c9ac',
        'inverse-surface': '#dfe2ee',
        'inverse-on-surface': '#2c3039',
        outline: '#8e9379',
        'outline-variant': '#444933',
        'surface-tint': '#abd600',
        primary: {
          DEFAULT: '#ffffff',
          on: '#283500',
          container: '#c3f400',
          'on-container': '#556d00',
          inverse: '#506600',
        },
        secondary: {
          DEFAULT: '#4cd7f6',
          on: '#003640',
          container: '#03b5d3',
          'on-container': '#00424e',
        },
        tertiary: {
          DEFAULT: '#ffffff',
          on: '#1f3700',
          container: '#acf847',
          'on-container': '#457000',
        },
        error: {
          DEFAULT: '#ffb4ab',
          on: '#690005',
          container: '#93000a',
          'on-container': '#ffdad6',
        },
        background: '#0f131c',
        'on-background': '#dfe2ee',
        'surface-variant': '#31353e',
      },
      fontFamily: {
        display: ['"Space Grotesk"', 'sans-serif'],
        body: ['"Plus Jakarta Sans"', 'sans-serif'],
      },
      spacing: {
        xs: '0.25rem',
        sm: '0.5rem',
        md: '1rem',
        lg: '1.5rem',
        xl: '2rem',
        gutter: '1.5rem',
        margin: '2rem',
      },
      fontSize: {
        xs: ['0.75rem', { lineHeight: '1rem' }],
        sm: ['0.875rem', { lineHeight: '1.25rem' }],
        base: ['1rem', { lineHeight: '1.5rem' }],
        lg: ['1.125rem', { lineHeight: '1.75rem' }],
        xl: ['1.25rem', { lineHeight: '1.75rem' }],
        '2xl': ['1.5rem', { lineHeight: '2rem' }],
        // Apex Core type scale
        'display-hero': ['56px', { lineHeight: '64px', letterSpacing: '-0.03em', fontWeight: '700' }],
        'headline-xl': ['40px', { lineHeight: '48px', letterSpacing: '-0.02em', fontWeight: '700' }],
        'headline-lg': ['32px', { lineHeight: '40px', letterSpacing: '-0.02em', fontWeight: '700' }],
        'headline-md': ['24px', { lineHeight: '32px', letterSpacing: '-0.01em', fontWeight: '600' }],
        'headline-sm': ['20px', { lineHeight: '28px', letterSpacing: '0', fontWeight: '600' }],
        'metric-huge': ['48px', { lineHeight: '52px', letterSpacing: '-0.03em', fontWeight: '700' }],
        'metric-lg': ['32px', { lineHeight: '36px', letterSpacing: '-0.02em', fontWeight: '700' }],
        'metric-md': ['20px', { lineHeight: '24px', letterSpacing: '0', fontWeight: '600' }],
        'body-lg': ['18px', { lineHeight: '28px', fontWeight: '400' }],
        'body-md': ['15px', { lineHeight: '24px', fontWeight: '400' }],
        'body-sm': ['13px', { lineHeight: '20px', fontWeight: '400' }],
        'label-caps': ['11px', { lineHeight: '14px', letterSpacing: '0.12em', fontWeight: '700' }],
        'label-md': ['13px', { lineHeight: '18px', letterSpacing: '0.02em', fontWeight: '600' }],
        caption: ['11px', { lineHeight: '16px', letterSpacing: '0.01em', fontWeight: '500' }],
      },
    },
  },
  plugins: [],
} satisfies Config
